# Generated by Django 4.2.19 on 2025-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('ME', 'Mechanical'), ('EE', 'Electrical')], max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
